[opener]
image = [
{ run = 'swayimg "$@"', orphan = true, desc = "swayimg", for = "unix" }
]

edit=[
{run= 'nvim "$@"',block = true}
]
broswer=[
{run= 'brave-broswer "$@"',orphan=true}
]
[open]
rules = [
{ mime = "image/*", use = "image" },
{mime = "text/*",use="edit"},
{mime = "application/pdf",use="broswer"}
]

